import { useCopyButton } from "#/hooks/use-copy-button.ts";
import { cn } from "#/lib/utils.ts";
import { HugeiconsIcon } from "@hugeicons/react";
import { Button } from "../ui/button";
import { Copy01Icon, Tick01Icon } from "@hugeicons/core-free-icons";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import { createContext, use, useMemo, useRef } from "react";
import { mergeRefs } from "#/lib/merge-refs.ts";

export type CodeBlockProps = React.ComponentProps<"figure"> & {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: React.ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: React.HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  Actions?: (props: { className?: string; children?: React.ReactNode }) => React.ReactNode;
};

const TabsContext = createContext<{
  containerRef: React.RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: React.ComponentProps<"pre">) {
  return (
    <pre {...props} className={cn("min-w-full w-max *:flex *:flex-col mt-0", props.className)}>
      {props.children}
    </pre>
  );
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => <div {...props} className={cn("empty:hidden", props.className)} />,
  ...props
}: CodeBlockProps) {
  const inTab = use(TabsContext) !== null;
  const areaRef = useRef<HTMLDivElement>(null);

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={-1}
      className={cn(
        inTab ? "-mx-px -mb-px last:rounded-b-xl mt-0" : "my-4 rounded-xl",
        keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",
        "bg-muted shiki relative border not-prose overflow-hidden text-sm",
        props.className,
      )}
    >
      {title ? (
        <div className="flex text-xs text-muted-foreground items-center gap-2 h-8 border-b px-[1em]">
          {typeof icon === "string" ? (
            <div
              className="[&_svg]:size-3"
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            icon
          )}
          <figcaption className="flex-1 truncate mt-0 text-left">{title}</figcaption>
          {Actions({
            className: "-me-2",
            children: allowCopy && <CopyButton containerRef={areaRef} />,
          })}
        </div>
      ) : (
        Actions({
          className:
            "absolute top-0.75 right-0.75 z-2 backdrop-blur-lg rounded-lg text-muted-foreground",
          children: allowCopy && <CopyButton containerRef={areaRef} />,
        })
      )}
      <div
        ref={areaRef}
        {...viewportProps}
        role="region"
        tabIndex={0}
        className={cn(
          "text-[0.9286em] relative overflow-auto max-h-150 scroll-container scrollbar-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring",
          viewportProps.className,
        )}
        style={
          {
            // space for toolbar
            "--padding-right": !title ? "calc(var(--spacing) * 6)" : undefined,
            counterSet: props["data-line-numbers"]
              ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
              : undefined,
            ...viewportProps.style,
          } as object
        }
      >
        <div className="w-full">{children}</div>
      </div>
    </figure>
  );
}

function CopyButton({
  className,
  containerRef,
  ...props
}: React.ComponentProps<"button"> & {
  containerRef: React.RefObject<HTMLElement | null>;
}) {
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.replaceWith("\n");
    });

    void navigator.clipboard.writeText(clone.textContent ?? "");
  });

  return (
    <Button
      variant="ghost"
      data-checked={checked || undefined}
      size="icon-sm"
      className={cn(className)}
      aria-label={checked ? "Copied Text" : "Copy Text"}
      onClick={onClick}
      {...props}
    >
      {checked ? <HugeiconsIcon icon={Tick01Icon} /> : <HugeiconsIcon icon={Copy01Icon} />}
    </Button>
  );
}

export function CodeBlockTabs({
  ref,
  className,
  children,
  ...props
}: Omit<React.ComponentProps<typeof Tabs>, "className"> & { className?: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const nested = use(TabsContext) !== null;

  return (
    <Tabs
      ref={mergeRefs(containerRef, ref)}
      {...props}
      className={cn(
        "bg-muted rounded-xl border gap-0",
        {
          "my-4": !nested,
        },
        className,
      )}
    >
      <TabsContext
        value={useMemo(
          () => ({
            containerRef,
            nested,
          }),
          [nested],
        )}
      >
        {children}
      </TabsContext>
    </Tabs>
  );
}

export function CodeBlockTabsList({
  className,
  ...props
}: Omit<React.ComponentProps<typeof TabsList>, "className"> & { className?: string }) {
  return <TabsList variant="line" className={cn("px-3", className)} {...props} />;
}

export function CodeBlockTabsTrigger({
  className,
  ...props
}: React.ComponentProps<typeof TabsTrigger>) {
  return <TabsTrigger className={cn("text-xs", className)} {...props} />;
}

export function CodeBlockTab(props: React.ComponentProps<typeof TabsContent>) {
  return <TabsContent {...props} />;
}
