packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

allowBuilds:
  esbuild: true
  lightningcss: true

catalog:
  "@changesets/cli": ^2.31.1
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
